name: Gitee repos mirror periodic job

on:
  push:
  pull_request:
    paths:
      - ".github/workflows/gitee-repos-mirror.yml"
    # Runs at every pull requests submitted in master branch
    branches: [main]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@v1.0
        with:
          src: github/pure-admin-backend
          dst: gitee/pure-admin-backend
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          timeout: 600
          force_update: true
